#!/bin/sh

# comment out '-DPC' on smaller screens

stack ghc -- \
  --make xmobar.hs \
  -DPC \
  -threaded \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -v0

rm *.o *.hi

cp ./xmobar ~/.local/bin/xmobar
