#!/bin/sh

exec ghc           \
  --make xmobar.hs \
  -package xmobar  \
  # -i               \
  -ilib            \
  -fforce-recomp   \
  -main-is main    \
  -v0              \
  -o "$1"          \

