#!/bin/sh

while read -r line; do
    CONFIG_PATH=$HOME/`echo $line | awk '{print $1}'`
    FOLDER=`echo $line | awk '{print $2}'`
    COPY_PATH="$HOME/Backup/dotfiles/$FOLDER"
    echo "Gathering" $CONFIG_PATH
    mkdir -p $COPY_PATH && cp -r $CONFIG_PATH $COPY_PATH
done < /home/martin/Backup/dotfiles/backup-list
