#!/bin/bash

while read -r LINE; do
    FOLDER=$(echo "$LINE" | awk '{print $1}')
    CONFIG_PATH=$(echo "$LINE" | awk '{print $2}')
    CONFIG_PATH=${CONFIG_PATH//\~/$HOME}
    COPY_PATH="$HOME/Backup/dotfiles/$FOLDER"
    echo "Gathering $CONFIG_PATH"
    mkdir -p "$COPY_PATH" && cp -r $CONFIG_PATH "$COPY_PATH"
done < ./backup-list
