#!/bin/sh

yay -S kitty \
    fish \
    rofi \
    macchina \
    neovim \
    picom-jonaburg-git \
    ranger \
    discord \
    timeshift-autosnap \
    nomacs \
    xautolock \
    zathura \
    zathura-pdf-poppler \
    thunar \
    flameshot \
    find-the-command-git \
    caprine \
    cbonsai \
    nvtop \
    htop \
    btop \
    ttf-fira-code

cp kitty "$HOME/.config/"
