#!/bin/bash

PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.cabal/bin:$PATH"
PATH="$HOME/.ghcup/bin:$PATH"

yay -S --noconfirm       \
    kitty                \
    vlc                  \
    fish                 \
    rofi                 \
    macchina             \
    neovim               \
    ranger               \
    discord              \
    qutebrowser          \
    timeshift-autosnap   \
    nomacs               \
    xautolock            \
    zathura              \
    zathura-pdf-poppler  \
    thunar               \
    flameshot            \
    find-the-command-git \
    caprine              \
    cbonsai              \
    nvtop                \
    htop                 \
    btop                 \
    ttf-fira-code        \
    ttf-roboto           \
    ttf-font-awesome     \
    ghcup-hs-bin         \
    dropbox              \
    gnome-keyring        \
    libsecret            \
    trash                \
    imwheel

yay -S picom-jonaburg-git
chsh -s $(which fish)

CONFIGS="kitty nvim xmobar xmonad macchina picom fish confedit qutebrowser ranger rofi"

for DIR in $CONFIGS; do
    cp -r "$DIR" "$HOME/.config/"
done

# Install vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

mkdir "$HOME/.local/bin" || echo "~/.local/bin already exists"
cp -r ./scripts/* "$HOME/.local/bin/"
cp ./xsession-pc/.xsession "$HOME/"
cp ./mimeapps/mimeapps.list "$HOME/.config"

cd "$HOME" || exit 1

ghcup install ghc
ghcup set ghc 8.10.7
ghcup install cabal

cabal update

cabal install pandoc   \
    ShellCheck         \
    flippers           \
    stylish-haskell    \
    text-format-simple \
    xmonad

cabal install --lib xmonad xmonad-contrib
cabal install xmobar --flags="all_extensions"

cd "$HOME/Downloads/" || exit 1

curl -O "https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh"

bash ./Anaconda*

conda update conda

conda create --name dev
conda create --name nvim

conda install -c conda-forge -n nvim neovim2
