#!/bin/bash


CONFIGS="kitty nvim xmobar xmonad macchina picom fish confedit qutebrowser ranger rofi"

for DIR in $CONFIGS; do
    cp -r "$DIR" "$HOME/.config/"
done

cp -r ./scripts/* "$HOME/.local/bin/"
