#!/bin/sh

TERM='kitty --class=kitty-float'
X=$(pgrep -fac "$TERM -e $1")
PID=$(pgrep -fa "$TERM -e $1" | awk '{print $1}' | head -n 1)

if [ "$X" -gt 0 ];
    then kill "$PID"
    else $TERM -e "$1" &
fi
