#!/bin/bash

TERM="kitty --class=kitty-float"
X=$(ps ax | grep "$TERM -e $1" | wc -l)
PID=$(ps ax | grep "$TERM -e $1" | awk '{print $1}' | head -n 1)

if [ "$X" -gt 1 ];
    then kill "$PID"
    else $TERM -e "$1" &
fi
