#!/bin/sh

exec ghc           \
  --make xmonad.hs \
  -package X11     \
  -package text-format-simple \
  -package flippers \
  -i               \
  -ilib            \
  -fforce-recomp   \
  -main-is main    \
  -v0              \
  -o "$1"
