#!/bin/bash

LOCK=/var/local/change_theme/light_on.lck

if [ -f $LOCK ]
then
    THEME="dark"
    rm $LOCK
else
    THEME="light"
    touch $LOCK
fi

KITTY_CONF=$HOME/.config/kitty
cat $KITTY_CONF/$THEME.theme > $KITTY_CONF/current.theme

for pid in $(ps -ef | awk '/kitty/ {print $2}' | head -n -1)
do
    kill -s SIGUSR1 $pid
done
# fish -c refresh-kitty

nitrogen --set-zoom-fill $HOME/Pictures/Wallpapers/wallpaper-$THEME.png --save

VIM_CONFIG=$HOME/.config/nvim/init.vim

for SERVER in $(nvr --nostart --serverlist)
do
    nvr --servername $SERVER --remote -cc "so ${VIM_CONFIG}"
done

