#!/bin/bash
LOCK=/var/local/change_theme/light_on.lck

if [ -f $LOCK ]
then
    THEME="dark"
    rm $LOCK
else
    THEME="light"
    touch $LOCK
fi

$HOME/anaconda3/bin/wal -f $HOME/.config/wal/colorschemes/$THEME/w_$THEME.json

nitrogen --set-zoom-fill $HOME/Pictures/Wallpapers/wallpaper-$THEME.png --save


