#!/bin/bash

getopts ":e" opt

while read -r line; do
    config_name=$(echo $line | cut -d ' ' -f 1)
    config_path=$(echo $line | cut -d ' ' -f 2-)
    if [ "$config_name" = "${*: -1}" ]; then break; fi
done < "$HOME/.config/confedit/confedit.list"

sed_path=${config_path//\~/"$HOME"}

if [[ $SHLVL -gt 1 && $opt != "e" ]]
then
    nvim $sed_path
else
    kitty -e nvim "$sed_path"
fi
