#!/bin/bash

getopts ":e" opt

while IFS= read -r LINE; do
    CONFIG_NAME=$(echo "$LINE" | awk '{print $1}')
    CONFIG_PATH=$(echo "$LINE" | awk '{print $2}')
    if [ "$CONFIG_NAME" = "${*: -1}" ]; then break; fi
done < "$HOME/.config/confedit/confedit.list"

SED_PATH=${CONFIG_PATH//\~/"$HOME"}

if [[ $SHLVL -gt 1 && $opt != "e" ]]
then
    nvim "$SED_PATH"
else
    kitty -e nvim "$SED_PATH"
fi
